name: Build Inspector

on:
  push:
    tags:
      - '*'

jobs:
  build_and_upload_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Build
      working-directory: packages/isar_inspector
      run: |
        flutter config --enable-macos-desktop
        flutter build macos
    - name: Compress
      working-directory: packages/isar_inspector/build/macos/Build/Products/Release/
      run: zip -r -y inspector.zip "Isar Inspector.app"
    - name: Upload binary
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: packages/isar_inspector/build/macos/Build/Products/Release/inspector.zip
        asset_name: Isar_Inspector_MacOS.zip
        tag: ${{ github.ref }}

  build_and_upload_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install Linux requirements
        run: |
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Build
        working-directory: packages/isar_inspector
        run: |
          flutter config --enable-linux-desktop
          flutter build linux
      - name: AppImage
        uses: addnab/docker-run-action@v3
        with:
          image: lil5/appimage-builder:1.0.0-go-alpha
          options: -v ${{ github.workspace }}:/app
          shell: bash
          run: |
            cd /app/packages/isar_inspector/linux/appimage
            VERSION=${{ github.ref }} appimage-builder --recipe AppImageBuilder.yml --skip-test
      - name: Upload binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/isar_inspector/linux/appimage/Isar_Inspector_Linux.AppImage
          asset_name: Isar_Inspector_Linux.AppImage
          tag: ${{ github.ref }}
